### ISSUE TITLE
Allow `classifyVariants` to take scores by `aa_substitutions`

### ISSUE THREAD

**Issue by ajgreaney** [jbloomlab/dms_variants#49]
@jbloom The [classifyVariants](https://jbloomlab.github.io/dms_variants/dms_variants.codonvarianttable.html?highlight=escape_scores#dms_variants.codonvarianttable.CodonVariantTable.classifyVariants) function will not work on a dataframe of `func_scores` or `escape_scores` that have been calculated by `aa_substitutions`, as the input dataframe for this function must have columns named `aa_substitutions`, `n_aa_substitutions`, and `n_codon_substitutions`, and scores calculated `by_aa_substitutions` will lack the ‘n_codon_substitutions’ column. 

There are hacky ways to get around this, but it would be great if the `classifyVariants` function would work directly on the output from `func_scores` or `escape_scores` when calculated by `aa_substitutions`.

**Comment by jbloom** [comment]
@ajgreaney, it should work if you set `syn_as_wt=True` (see [here](https://jbloomlab.github.io/dms_variants/dms_variants.codonvarianttable.html?highlight=classifyvariants#dms_variants.codonvarianttable.CodonVariantTable.classifyVariants)).

I think this is the correct behavior: if the statistic is being calculated by amino-acid substitutions, then the classification has to be categorizing synonymous variants as wildtype, so that should be explicitly specified.

I'm closing this issue, but feel free to re-open if this does not fix the problem.
